moving to github container registry: build deploy

diff --git a/.github/workflows/deploy-to-digitalocean.yml b/.github/workflows/deploy-to-digitalocean.yml
--- a/.github/workflows/deploy-to-digitalocean.yml
+++ b/.github/workflows/deploy-to-digitalocean.yml
@@ -49,7 +49,17 @@ jobs:
             echo "Logging into the Container Registry..."
             echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.CONTAINER_REGISTRY }} -u ${{ github.actor }} --password-stdin
             
-            docker pull ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ GITHUB.SHA }} || { echo "Failed to pull Docker image."; exit 1; }
+            success=false
+            for attempt in {1..5}; do
+              docker pull ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ GITHUB.SHA }} && success=true && break
+              echo "Attempt $attempt failed. Retrying in 10 seconds..."
+              sleep 10
+            done
+            
+            if [ "$success" = false ]; then
+              echo "Failed to pull Docker image after 5 attempts."
+              exit 1
+            fi
 
             docker stop $IMAGE_NAME || echo "No existing container to stop."
             docker rm $IMAGE_NAME || echo "No existing container to remove."
