moving to github container registry: build deploy

diff --git a/.github/workflows/deploy-to-digitalocean.yml b/.github/workflows/deploy-to-digitalocean.yml
--- a/.github/workflows/deploy-to-digitalocean.yml
+++ b/.github/workflows/deploy-to-digitalocean.yml
@@ -51,24 +51,28 @@ jobs:
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            echo $CONTAINER_REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG
-            docker pull $CONTAINER_REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG || { echo "Failed to pull Docker image."; exit 1; }
+            FILL_IMAGE_NAME="${{ env.CONTAINER_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
+            
+            echo "Pulling image: $FILL_IMAGE_NAME"
+            docker pull $FILL_IMAGE_NAME || { echo "Failed to pull Docker image."; exit 1; }
+            
             docker stop $IMAGE_NAME || echo "No existing container to stop."
             docker rm $IMAGE_NAME || echo "No existing container to remove."
             docker network create my-network || echo "Network already exists."
 
-            echo "Starting new Docker container..."
-            docker run -d \
-            --name $IMAGE_NAME \
-            -e TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
-            -e TELEGRAM_AUTHORIZED_USER_IDS="${{ vars.TELEGRAM_AUTHORIZED_USER_IDS }}" \
-            -e OPEN_WEATHER_MAP_API_KEY="${{ secrets.OPEN_WEATHER_MAP_API_KEY }}" \
-            -e OPEN_EXCHANGE_RATES_APP_ID="${{ secrets.OPEN_EXCHANGE_RATES_APP_ID }}" \
-            -e QUOTES_REST_API_KEY="${{ secrets.QUOTES_REST_API_KEY }}" \
-            -e DATABASE_URL=${{ vars.DATABASE_URL }} \
-            --network my-network \
-            $CONTAINER_REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_TAG
-
+            echo "Starting a new container..."
+            docker run --detach \
+              --name $IMAGE_NAME \
+              --env TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
+              --env TELEGRAM_AUTHORIZED_USER_IDS="${{ vars.TELEGRAM_AUTHORIZED_USER_IDS }}" \
+              --env OPEN_WEATHER_MAP_API_KEY="${{ secrets.OPEN_WEATHER_MAP_API_KEY }}" \
+              --env OPEN_EXCHANGE_RATES_APP_ID="${{ secrets.OPEN_EXCHANGE_RATES_APP_ID }}" \
+              --env QUOTES_REST_API_KEY="${{ secrets.QUOTES_REST_API_KEY }}" \
+              --env DATABASE_URL=${{ vars.DATABASE_URL }} \
+              --network my-network \
+              $FILL_IMAGE_NAME
+            
+            echo "Waiting for the container to start"
             RETRY=5
             while [ $RETRY -gt 0 ]; do
               if docker ps | grep -q $IMAGE_NAME; then
@@ -76,7 +80,7 @@ jobs:
                 break
               else
                 ((RETRY--))
-                echo "Waiting for the container to start. Retries left: $RETRY"
+                echo "Retries left: $RETRY"
                 sleep 5
               fi
             done
@@ -87,5 +91,5 @@ jobs:
               exit 1
             fi
             
-            #echo "Cleaning up..."
-            docker system prune -a -f
+            echo "Cleaning up unused resources"
+            docker system prune --all --force
