moving to github container registry: build deploy

diff --git a/.github/workflows/deploy-to-digitalocean.yml b/.github/workflows/deploy-to-digitalocean.yml
--- a/.github/workflows/deploy-to-digitalocean.yml
+++ b/.github/workflows/deploy-to-digitalocean.yml
@@ -9,13 +9,11 @@ env:
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  build-and-push-image:
+  build:
     runs-on: ubuntu-latest
-
     permissions:
       contents: read
       packages: write
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -36,7 +34,7 @@ jobs:
 
   deploy:
     runs-on: ubuntu-latest
-
+    needs: build
     steps:
       - name: Deploy to Digital Ocean droplet via SSH
         uses: appleboy/ssh-action@v0.1.4
@@ -47,19 +45,8 @@ jobs:
           envs: IMAGE_NAME,CONTAINER_REGISTRY,GITHUB_SHA
           script: |
             echo "Logging into the Container Registry..."
-            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.CONTAINER_REGISTRY }} -u ${{ github.actor }} --password-stdin
-            
-            success=false
-            for attempt in {1..5}; do
-              docker pull ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ GITHUB.SHA }} && success=true && break
-              echo "Attempt $attempt failed. Retrying in 10 seconds..."
-              sleep 10
-            done
-            
-            if [ "$success" = false ]; then
-              echo "Failed to pull Docker image after 5 attempts."
-              exit 1
-            fi
+            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.CONTAINER_REGISTRY }}
+            docker pull $CONTAINER_REGISTRY/$IMAGE_NAME:$GITHUB_SHA || { echo "Failed to pull Docker image."; exit 1; }
 
             docker stop $IMAGE_NAME || echo "No existing container to stop."
             docker rm $IMAGE_NAME || echo "No existing container to remove."
